#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-rag"
compatibility_date = "2024-08-21"
pages_build_output_dir = "./build/client"

[placement]
mode = "smart"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "cloudflare-rag-index"

[[d1_databases]]
binding = "DB"                                       
database_name = "cloudflare-rag"
database_id = "af3dd2a6-edc0-40cd-919d-f010bd088d18" # replace with your database id
migrations_dir = "drizzle"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "cloudflare-rag-bucket"

[[kv_namespaces]]
binding = "rate_limiter"
id = "8c126b8a543e4e15a0c4a3bd1f004ccd" # replace with your KV id
